version: '3'
services:
  app:
    build: app
    ports:
      - 8000:8000
    volumes:
      - ./visualize:/usr/src/app
    stdin_open: true
    working_dir: /usr/src/app
    command: npm run serve
  transformer:
    build: ./docker_transformer
    volumes:
      - ./jp_transformer:/work
      - ./attention_weight/:/attention_weight
      - ./bert_input_ids/:/bert_input_ids
    working_dir: /work
    tty: true
  calc_attention:
    build: ./docker_calc_attention
    volumes:
      - ./calc_attention:/work
      - ./attention_weight/:/attention_weight:ro
      - ./bert_input_ids/:/bert_input_ids:ro
      - ./visualize/src/assets:/features
    working_dir: /work
    tty: true
